#pragma once
#include <QString>
#include <qmath.h>

#define GET_RADIANS(angle) (angle * M_PI / 180)
#define GROUP_SEPARATE_CHAR QChar(0x1F)
#define FIELD_SEPARATE_CHAR QChar(0x1E)
#define DEFAULT_FONT_FAMILY "SimSun"
#define DEFAULT_FONT_WEIGHT 400
#define SAFE_DISTANCE 34
#define SCOPED_BRANCH_BASE 8
#define SCOPED_BRANCH_STEP 14
#define SCOPED_TRUNK_BASE 10
#define SCOPED_LANE_STEP 32
#define SCOPED_DOGLEG_STEP 12
#define SCOPED_LAYOUT_REFINE_PASSES 6
#define SCOPED_SIDE_MARGIN 80
#define SCOPED_ROW_GAP 70
#define SCOPED_TOP_LAYER_Y 220
#define SCOPED_BASE_LAYER_GAP_Y 170
#define SCOPED_SWITCH_GAP_Y 55
#define IED_OPTICAL_HORIZONTAL_DISTANCE 50
#define IED_OPTICAL_VERTICAL_DISTANCE 150
#define IED_OPTICAL_SWITCHER_WIDTH_RATIO 0.75
#define IED_OPTICAL_MIDPOINT_DISTANCE 10
#define OPTICAL_ARROW_EXTRA_OFFSET 5
#define OPTICAL_DOUBLE_ARROW_GAP_RATIO 2
