#ifndef CIRCUITMODULE_GLOBAL_H
#define CIRCUITMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CIRCUITMODULE_LIBRARY)
#  define CIRCUITMODULE_API Q_DECL_EXPORT
#elif defined(CIRCUITMODULE_SHARED) || defined(CIRCUITMODULE_DLL) || defined(CIRCUITMODULE_IMPORT)
#  define CIRCUITMODULE_API Q_DECL_IMPORT
#else
#  define CIRCUITMODULE_API
#endif

#endif // CIRCUITMODULE_GLOBAL_H
